#! /bin/sh

bspc config normal_border_color dimgray
bspc config focused_border_color dodgerblue
bspc config border_width        5
bspc config window_gap         10
bspc config split_ratio           0.618 # Golden ratio!
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true

bspc monitor -d I II III IV V

bspc rule -a urxvt_floating floating=on
