#! /bin/sh

bspc config active_border_color "#5788ff"
bspc config border_width        2
bspc config window_gap         12
bspc config split_ratio           0.618 # Golden ratio!
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true

bspc monitor -d I II III IV V

bspc rule -a urxvt_floating floating=on
